function A = A_arm(in1,in2)
%A_arm
%    A = A_arm(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    08-Nov-2022 14:48:47

I1 = in2(5,:);
I2 = in2(6,:);
I3 = in2(7,:);
I4 = in2(8,:);
Ir = in2(9,:);
N = in2(10,:);
l_AC = in2(17,:);
l_A_m3 = in2(13,:);
l_B_m2 = in2(12,:);
l_C_m4 = in2(14,:);
l_OA = in2(15,:);
l_OB = in2(16,:);
l_O_m1 = in2(11,:);
m1 = in2(1,:);
m2 = in2(2,:);
m3 = in2(3,:);
m4 = in2(4,:);
th2 = in1(2,:);
t2 = cos(th2);
t3 = N.^2;
t4 = l_AC.^2;
t5 = l_A_m3.^2;
t6 = l_B_m2.^2;
t7 = l_OA.^2;
t8 = Ir.*N;
t9 = Ir.*t3;
t10 = m4.*t4;
t11 = m3.*t5;
t12 = m2.*t6;
t13 = l_AC.*l_C_m4.*m4.*t2;
t14 = l_AC.*l_OA.*m4.*t2;
t15 = l_A_m3.*l_OA.*m3.*t2;
t16 = l_B_m2.*l_OB.*m2.*t2;
t17 = I2+I3+t8+t10+t11+t12+t13+t14+t15+t16;
A = reshape([I1+I2+I3+I4+Ir+t9+t10+t11+t12+t13.*2.0+t14.*2.0+t15.*2.0+t16.*2.0+m3.*t7+m4.*t7+l_C_m4.^2.*m4+l_OB.^2.*m2+l_O_m1.^2.*m1+l_C_m4.*l_OA.*m4.*2.0,t17,t17,I2+I3+t9+t10+t11+t12],[2,2]);
