function Corr_Joint_Sp = Corr_arm(in1,in2)
%Corr_arm
%    Corr_Joint_Sp = Corr_arm(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    08-Nov-2022 15:13:30

dth1 = in1(3,:);
dth2 = in1(4,:);
l_AC = in2(17,:);
l_A_m3 = in2(13,:);
l_B_m2 = in2(12,:);
l_C_m4 = in2(14,:);
l_OA = in2(15,:);
l_OB = in2(16,:);
m2 = in2(2,:);
m3 = in2(3,:);
m4 = in2(4,:);
th2 = in1(2,:);
t2 = sin(th2);
t3 = l_AC.*l_C_m4.*m4;
t4 = l_AC.*l_OA.*m4;
t5 = l_A_m3.*l_OA.*m3;
t6 = l_B_m2.*l_OB.*m2;
t7 = t3+t4+t5+t6;
Corr_Joint_Sp = [-dth2.*t2.*t7.*(dth1.*2.0+dth2);dth1.^2.*t2.*t7];
