function Grav_Joint_Sp = Grav_arm(in1,in2)
%Grav_arm
%    Grav_Joint_Sp = Grav_arm(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
<<<<<<< HEAD:matlab_code/auto_derived/Grav_leg.m
%    08-Nov-2022 14:48:48
=======
%    08-Nov-2022 15:13:30
>>>>>>> origin/main:matlab_code/auto_derived/Grav_arm.m

g = in2(19,:);
l_AC = in2(17,:);
l_A_m3 = in2(13,:);
l_B_m2 = in2(12,:);
l_C_m4 = in2(14,:);
l_OA = in2(15,:);
l_OB = in2(16,:);
l_O_m1 = in2(11,:);
m1 = in2(1,:);
m2 = in2(2,:);
m3 = in2(3,:);
m4 = in2(4,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = sin(th1);
t3 = th1+th2;
t4 = l_OA.*t2;
t5 = sin(t3);
Grav_Joint_Sp = [g.*m2.*(l_B_m2.*t5+l_OB.*t2)+g.*m3.*(t4+l_A_m3.*t5)+g.*m4.*(t4+l_AC.*t5+l_C_m4.*t2)+g.*l_O_m1.*m1.*t2;g.*t5.*(l_AC.*m4+l_A_m3.*m3+l_B_m2.*m2)];
