function keypoints = keypoints_arm(in1,in2)
%KEYPOINTS_ARM
%    KEYPOINTS = KEYPOINTS_ARM(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
<<<<<<< HEAD
%    08-Nov-2022 14:48:48
=======
%    08-Nov-2022 15:13:30
>>>>>>> origin/main

l_AC = in2(17,:);
l_DE = in2(18,:);
l_OA = in2(15,:);
l_OB = in2(16,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
t5 = l_OA.*t2;
t6 = l_OB.*t2;
t7 = cos(t4);
t8 = l_OA.*t3;
t9 = l_OB.*t3;
t10 = sin(t4);
t11 = l_AC.*t7;
t12 = l_AC.*t10;
t13 = -t5;
t14 = -t6;
t15 = -t11;
keypoints = reshape([t8,t13,t9,t14,t8+t12,t13+t15,t9+t12,t14+t15,t9+t12+l_DE.*t3,t14+t15-l_DE.*t2],[2,5]);
