function rE = position_arm(in1,in2)
%POSITION_ARM
%    rE = POSITION_ARM(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    10-Nov-2022 20:41:44

l_AC = in2(17,:);
l_DE = in2(18,:);
l_OB = in2(16,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
rE = [l_DE.*t3+l_OB.*t3+l_AC.*sin(t4);-l_DE.*t2-l_OB.*t2-l_AC.*cos(t4)];
